(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[39],{1385:function(C,F,b){function a(W){var G=fa.call(this)||this;G.Kc=W;G.Yb();return G}function e(W,G){this.Z8d=this.REc=!1;this.xKf=G;this.$=W;this.$.userOperationManager.jB(Object(h.a)(this,this.Iqf,"onQueueItemChange"));this.$.Jk(Object(h.a)(this,this.jd,"onWorkbookOpened"));this.$.fa.kug(Object(h.a)(this,this.Hrf,"onSaveStatusChange"));this.$.fa.Yj(Object(h.a)(this,this.Vc,"onSessionIdChanged"));this.$.NPc(Object(h.a)(this,
this.qBb,"onUserAlertActivityBeforeShow"));this.$.fa.nO(Object(h.a)(this,this.gq,"onLoadOnDemandOccurred"));this.Sca()}function d(){this.FKc=this.JJc=this.rib=this.Za=null}function l(W,G,N,Y){this.Bea=this.tea=this.Fea=this.Eea=null;this.jCa=0;this.bD=this.EKc=this.AAa=this.mzc=this.fDa=null;this.Qd=W;this.s7=G;this.u0=N;this.Vi=Y;this.s1d=!0;this.JK=!1;this.dz=3;this.lpa=!0}function n(W,G){this.rr=null;this.Eea=CommonUIStrings.l_SavedStatus;this.Fea=CommonUIStrings.l_SavingStatus;this.tea=CommonUIStrings.l_ReadOnlyStatus;
this.Bea=CommonUIStrings.l_ReviewModeStatus;this.POb=G;this.u0=W;this.dz=3;this.lpa=!0}function r(W){this.Bea=this.tea=this.Fea=this.Eea=null;this.O2d=this.fw=this.JK=!1;this.SJc=this.d3d=null;this.V2d=0;this.vb=this.a3d=null;this.u0=W;this.dz=3;this.Zfb=!0}b.r(F);C=b(0);var h=b(37),v=b(15),w=b(213),t=b(48);r.prototype.initialize=function(W,G,N){var Y=this;this.Eea=this.qad(W,G);this.Fea=CommonUIStrings.l_SavingStatus;this.tea=CommonUIStrings.l_ReadOnlyStatus;this.Bea=CommonUIStrings.l_ReviewModeStatus;
this.u0&&this.u0.execute(function(V){V.IPc(Object(h.a)(Y,Y.qKb,"updateToSavingStatus"))});this.fw=!0;this.vb=N;return!0};r.prototype.Sca=function(W,G){this.JK=W;this.dz=G;this.cR(this.Zfb)};r.prototype.cR=function(W){!this.Zfb&&W&&(this.a3d=new Date);this.Zfb=W;W=null;3===this.dz&&(W=this.Zfb?this.Eea:this.Fea);this.D3g(W)};r.prototype.qad=function(W,G){return W?String.format(CommonUIStrings.l_SavedToStatus,CommonUIStrings.l_OneDriveName):G&&G.length?String.format(CommonUIStrings.l_SavedToStatus,
G):CommonUIStrings.l_SavedStatus};r.prototype.qKb=function(){this.cR(!1)};r.prototype.lDh=function(){switch(this.dz){case 1:return this.tea;case 2:return this.Bea;default:return null}};r.prototype.T0h=function(W){return this.O2d===this.JK&&this.V2d===this.dz&&this.d3d===W};r.prototype.fAe=function(W){var G=this;appChrome.getHeaderApi().then(function(N){N.updateDocumentTitleStatus(G.JK,W,G.lDh(),G.a3d,G.Zfb);return null});this.SJc=null};r.prototype.D3g=function(W){var G=this;this.fw&&w.appChromeAlreadyLoaded()&&
!this.T0h(W)&&(t.a.FHf()?(this.SJc&&v.ULS.sendTraceTag(595146389,340,50,"Previous UpdateDocumentTitleStatus idle callback can be cancelled."),this.SJc=window.requestIdleCallback(function(){G.fAe(W)})):window.requestAnimationFrame(function(){G.fAe(W)}),this.O2d=this.JK,this.d3d=W,this.V2d=this.dz)};Object(C.a)(r,"ReactSaveStatusUIHandler",null,[273]);var B=b(178);n.prototype.tx=function(){var W=this;this.u0&&this.u0.execute(function(G){G.IPc(Object(h.a)(W,W.qKb,"updateToSavingStatus"))});this.POb.execute(function(G){W.rr=
G})};n.prototype.Sca=function(W,G){this.dz=G;3===G?this.cR(this.lpa):2===G?this.KPd(this.Bea):this.KPd(this.tea)};n.prototype.qKb=function(){this.cR(!1)};n.prototype.cR=function(W){this.lpa=W;this.KPd(this.lpa?this.Eea:this.Fea)};n.prototype.KPd=function(W){this.rr&&this.rr.Vj(B.a.Vtj,this.APg(W))};n.prototype.APg=function(W){var G={};G.StatusText=W;return G};Object(C.a)(n,"SaveStatusPostMessageHandler",null,[273]);var z=b(816),x=b(164),y=b(85);l.prototype.initialize=function(W,G){if(!this.Qd)return!1;
this.Eea=this.qad(W,G);this.Fea=CommonUIStrings.l_SavingStatus;this.tea=CommonUIStrings.l_ReadOnlyStatus;this.Bea=CommonUIStrings.l_ReviewModeStatus;this.tx();return!0};l.prototype.qad=function(W,G){return W?String.format(CommonUIStrings.l_SavedToStatus,CommonUIStrings.l_OneDriveName):G&&G.length?String.format(CommonUIStrings.l_SavedToStatus,G):CommonUIStrings.l_SavedStatus};l.prototype.tx=function(){var W=this;this.s7&&this.s7.execute(function(G){G.Ltg(Object(h.a)(W,W.Gwe,"createStatusAndModeElements"));
G.Ctg(Object(h.a)(W,W.Egj,"showHideSaveStatusElement"));G.qrj&&W.Gwe(null,null)});this.u0&&this.u0.execute(function(G){G.IPc(Object(h.a)(W,W.qKb,"updateToSavingStatus"))})};l.prototype.Ou=function(){this.bD&&this.Qd&&this.Qd.dF(this.bD)};l.prototype.Egj=function(W,G){this.Sca("true"===G,this.dz)};l.prototype.Sca=function(W,G){this.JK=W;this.dz=G;this.mzc&&(this.mzc.style.display=this.JK||3===this.dz||!this.fDa?"none":"");this.AAa&&(this.AAa.style.display=this.JK||3===this.dz?"none":"",this.AAa.innerText=
1===this.dz?this.tea:this.Bea,this.AAa.title=1===this.dz?CommonUIStrings.l_ReadOnlyStatusTooltip:CommonUIStrings.l_ReviewModeStatusTooltip);this.EKc&&(this.EKc.style.display=this.JK||1===this.dz||!this.fDa&&!this.AAa?"none":"");this.bD&&(this.bD.style.display=this.JK||1===this.dz?"none":"",this.cR(this.lpa),this.bD.title=CommonUIStrings.l_SaveStatusTooltip)};l.prototype.Gwe=function(W,G){W=document.getElementById(z.CuiHelper.GZe);G&&G.TCj||!W||""===this.Eea||""===this.Fea||""===this.tea||""===this.Bea||
(this.fDa=document.getElementById(z.CuiHelper.EXb),this.mzc=z.CuiHelper.mra(W,"BreadcrumbAppModeDash","-",null,!1),this.AAa=z.CuiHelper.mra(W,"BreadcrumbAppModeStatus",1===this.dz?this.tea:this.Bea,null,!1),this.m2f(this.AAa),this.EKc=z.CuiHelper.mra(W,"BreadcrumbSaveStatusDash","-",null,!1),this.bD=z.CuiHelper.mra(W,"BreadcrumbSaveStatus",this.Eea,null,!1),this.m2f(this.bD),this.Sca(this.JK,this.dz))};l.prototype.qKb=function(){this.cR(!1)};l.prototype.cR=function(W){this.lpa=W;this.Lyj(this.lpa?
this.Eea:this.Fea)};l.prototype.Lyj=function(W){!this.bD||3!==this.dz&&2!==this.dz||(this.s1d&&!this.lpa?(this.jCa=this.bD.offsetWidth<this.jCa?this.jCa:this.bD.offsetWidth,this.Rvj(this.Fea),this.s1d=!1):this.bD.innerText=W)};l.prototype.m2f=function(W){W.style.direction=this.Vi?"rtl":"ltr";W.style.width="auto";W.style.textAlign=this.Vi?"right":"left";W.style.display=this.JK?"none":"";W.setAttribute("Unselectable","on")};l.prototype.Rvj=function(W){this.bD&&(this.bD.style.width="",this.bD.innerText=
W,this.jCa=this.bD.offsetWidth<this.jCa?this.jCa:this.bD.offsetWidth,W=x.a.Sz(this.bD),this.bD.style.width=this.jCa-y.a.nC(W.paddingLeft)-y.a.nC(W.paddingRight)+1+"px")};Object(C.a)(l,"SaveStatusUIHandler",null,[273]);var J=b(5),E=b(97);d.prototype.Qh=function(W){var G=this;this.Za=W;J.AFrameworkApplication.ha.sa("PostMessageEmbedded")&&J.AFrameworkApplication.hideHeaderEmbedded?this.Za.register(n,"Common.App.SaveStatus.SaveStatusPostMessageHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").wc().Fc(function(){return new n(G.Za.oc("Common.App.HostNotification.EditNotificationEventSource"),
G.Za.oc("Postmessage.IHostPostmessenger"))}):J.AFrameworkApplication.xa.Xa.O8e||(J.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled?this.Za.register(r,"Common.App.SaveStatus.ReactSaveStatusUIHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").wc().Fc(function(){return new r(G.Za.oc("Common.App.HostNotification.EditNotificationEventSource"))}):this.Za.register(l,"Common.App.SaveStatus.SaveStatusUIHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").wc().Fc(function(){return new l(E.EventHandlerManager.instance,
G.Za.oc("Common.App.Header.HeaderEventSource"),G.Za.oc("Common.App.HostNotification.EditNotificationEventSource"),J.AFrameworkApplication.isRtl)}))};d.prototype.init=function(){J.AFrameworkApplication.ha.Dv(Object(h.a)(this,this.mA,"onFullAppSettingsReady"))};d.prototype.mA=function(){var W=J.AFrameworkApplication.ha,G=!!J.AFrameworkApplication.xa.Xa&&4===J.AFrameworkApplication.xa.Xa.Tk;if(W.sa("WordEditorAutoSaveImprovementIsEnabled")||W.sa("PptEditorSaveStatusInHeaderEnabled")||G&&W.sa("SimplifiedReactRibbonUxIsEnabled")||
W.sa("ExcelSaveStatusInHeaderEnabled")||W.sa("VisioSaveStatusInHeaderEnabled"))J.AFrameworkApplication.ha.sa("PostMessageEmbedded")&&J.AFrameworkApplication.hideHeaderEmbedded?(this.FKc=this.Za.resolve("Common.App.SaveStatus.SaveStatusPostMessageHandler"))&&this.FKc.tx():J.AFrameworkApplication.xa.Xa.O8e||(J.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled?(this.JJc=this.Za.resolve("Common.App.SaveStatus.ReactSaveStatusUIHandler"))&&this.JJc.initialize(W.sa("IsSkyDrive"),W.Ta("HostNameToIncludeInSavedStatus"),
J.AFrameworkApplication.ha):(this.rib=this.Za.resolve("Common.App.SaveStatus.SaveStatusUIHandler"))&&this.rib.initialize(W.sa("IsSkyDrive"),W.Ta("HostNameToIncludeInSavedStatus")))};d.prototype.dispose=function(){this.rib&&this.rib.Ou()};Ll.Object.defineProperties(d.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.SaveStatus"}}});Object(C.a)(d,"PackageManager",null,[8,9]);F=b(276);var A=b(12),H=b(88),S=b(212),Q=b(216),L=b(27),aa=b(20);e.prototype.qBb=function(W,G){G&&
G.ZF&&L.a.Ayg([G.ZF])&&(this.Uoc=!0)};e.prototype.gq=function(){this.Uoc=!1};e.prototype.Vc=function(W,G){Q.b(G)&&this.Sca(!0);this.Uoc=!1};e.prototype.dispose=function(){this.$&&(this.$.dl(Object(h.a)(this,this.jd,"onWorkbookOpened")),this.$.vCd(Object(h.a)(this,this.qBb,"onUserAlertActivityBeforeShow")),this.$.userOperationManager&&this.$.userOperationManager.zC(Object(h.a)(this,this.Iqf,"onQueueItemChange")),this.$.fa&&(this.$.fa.GVi(Object(h.a)(this,this.Hrf,"onSaveStatusChange")),this.$.fa.qk(Object(h.a)(this,
this.Vc,"onSessionIdChanged")),this.$.fa.tV(Object(h.a)(this,this.gq,"onLoadOnDemandOccurred"))),aa.g(this.$)&&aa.g(this.$).Ca&&aa.g(this.$).Ca.Jq(Object(h.a)(this,this.Jsd,"onCacheConsistent")))};e.prototype.Sca=function(W){W=!this.$.isEditMode||(void 0===W?!1:W);this.xKf.Sca(W,this.$.isEditMode?3:1);this.cR()};e.prototype.cR=function(){this.$.isEditMode&&this.xKf.cR(!this.LP&&!this.V9h&&!this.Uoc)};e.prototype.jd=function(){this.LP=this.$.LP;this.Sca()};e.prototype.Hrf=function(){this.cR()};e.prototype.Iqf=
function(){this.LP=this.$.LP};e.prototype.Jsd=function(){aa.g(this.$).Ca.Jq(Object(h.a)(this,this.Jsd,"onCacheConsistent"));this.LP=this.$.LP};Ll.Object.defineProperties(e.prototype,{V9h:{configurable:!0,enumerable:!0,get:function(){return this.$.fa?this.$.fa.faf:!1}},LP:{configurable:!0,enumerable:!0,get:function(){return this.REc},set:function(W){W?this.REc=!0:aa.g(this.$)&&aa.g(this.$).Ca&&(aa.g(this.$).Ca.DG()?this.REc=!1:aa.g(this.$).Ca.Np(Object(h.a)(this,this.Jsd,"onCacheConsistent")));this.cR()}},
Uoc:{configurable:!0,enumerable:!0,get:function(){return this.Z8d},set:function(W){this.Z8d=W;this.cR()}}});Object(C.a)(e,"SaveStatusManager",null,[6]);var fa=S.a;Em(a,fa);a.prototype.create=function(){var W=this,G=H.a.instance;G.oc("Common.App.SaveStatus.ISaveStatusUIHandler").execute(function(N){var Y=new e(W.Kc,N);G.register(e,"Microsoft.Office.Excel.WebUI.Client.SaveStatus.SaveStatusManager").wc().Fc(function(){return Y});W.Eb(G.resolve("Microsoft.Office.Excel.WebUI.Client.SaveStatus.SaveStatusManager"))})};
a.ja=function(W){W.ea.Ia(299,new a(W))};Object(C.a)(a,"SaveStatusFactory",S.a,[]);Type.registerNamespace("_Ewa");Type.registerNamespace("Common.App.SaveStatus");F.a.instance.ej(new d);A.a.Ga(a.ja)}}]);

//# sourceMappingURL=EwaDS.savestatus.js.map