(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[33],{1374:function(C,F,b){function a(cb){return Qa.call(this,cb)||this}function e(cb){this.pi=cb}function d(cb){var Ab=fb.call(this)||this;Ab.renameFileManager=null;Ab.PX=null;Ab.$=cb;Ab.Yb();return Ab}function l(cb,Ab){var gc=jc.call(this)||this;gc.k0c=null;gc.cGf=null;gc.NCd=null;gc.Bba=null;gc.$=cb;gc.rr=Ab;gc.$.fa.Vs(Object(U.a)(gc,gc.uia,"handleWorkbookMetadataChanged"));return gc}function n(cb){this.$=cb}function r(cb){return cc.call(this,
cb)||this}function h(cb){this.renameFileManager=cb}function v(){this.vb=this.Za=null}function w(cb,Ab,gc,Lc,Nc,yd,Od,sa,vb,Lb){var rc=B.call(this,cb,gc,Lc,Nc,yd,vb)||this;rc.FTb=null;rc.dib=null;rc.thg=Ab;rc.La=Od;rc.fe=sa;Lb&&Lb.execute(function(Oc){rc.xRi(Oc)});return rc}function t(cb,Ab,gc,Lc,Nc,yd,Od,sa){cb=B.call(this,cb,Ab,gc,Lc,Nc,yd)||this;cb.V7d=Nc;cb.kig=Od;cb.Ldg=sa;return cb}function B(cb,Ab,gc,Lc,Nc,yd){this.gl=!1;this.HGc=new Ra.a;this.USa=Ab;this.EK=gc;this.dag=Lc;this.vb=Nc;this.I$d=
yd}function z(cb,Ab,gc,Lc,Nc){this.IAc=Nc;this.Z1d=gc;this.Y1d=Lc;this.Vlg=cb;this.moa=Ab}function x(cb){this.La=cb}function y(cb){this.h7=null;this.boa=0;this.La=cb;this._initialized=!1}function J(cb,Ab,gc){var Lc=lb.call(this)||this;Lc.La=cb;Lc.Vu=Ab;Lc.boa=gc;Lc.Ie="RenameDialog";Lc.tf=E.tf;return Lc}function E(){}function A(cb,Ab,gc){this.dialog=null;this.La=cb;this.Vu=Ab;this.boa=gc}function H(cb,Ab){this.La=cb;this.OSa=Ab}function S(){}function Q(cb,Ab,gc,Lc,Nc,yd,Od,sa,vb,Lb,rc,Oc){this.Y1d=
cb;this.La=Ab;this.IAc=gc;this.Vu=Lc;this.eCa=Nc;this.Rlg=yd;this.Fpa=Od;this.$ae=sa;this.mig=vb;this.moa=Lb;this.vb=rc;this.lig=Oc}function L(){this.Jki=this.Fki=this.rZg=null}function aa(){}function fa(cb,Ab,gc,Lc,Nc,yd,Od,sa,vb,Lb,rc,Oc){this._initialized=!1;this._element=null;this.kCa=0;this.QKc=this.pEc=!1;this.La=cb;this.Gzc=Ab;this.de=gc;this.pz=Lc;this.h7=Nc;this.b9d=yd;this.bSb=Od;this.yAc=sa;this.s7=vb;this.N1d=Lb;this.GTa=rc;this.iFc=Oc}function W(cb,Ab){this.kCa=0;this.La=cb;this.h7=Ab}
function G(cb,Ab,gc,Lc,Nc){var yd=ma.call(this)||this;yd.B0=new da(cb,Ab,gc);yd.Fpa=Lc;yd.moa=Nc;yd.Ie="RenameDisabledDialog";yd.hc=0;yd.yc(1,CommonUIStrings.l_DialogClose);yd.tf=N.tf;yd.showDialog(CommonUIStrings.l_RenameFileRenameDisabledTitle,null);yd.OV("RenameRow");return yd}function N(){}function Y(cb,Ab,gc,Lc,Nc){return V.call(this,cb,Ab,gc,Lc,Nc)||this}function V(cb,Ab,gc,Lc,Nc){var yd=La.call(this)||this;yd.VNd=[];yd.B0=new da(cb,Ab,gc);yd.Fpa=Lc;yd.moa=Nc;yd.Ie="RenameDisabledDialog";yd.hc=
0;yd.yc(1,CommonUIStrings.l_DialogClose);yd.X$i();yd.AWi();return yd}function da(cb,Ab,gc){this.HKd=this.IKd=this.JKd=!1;this.aLd=!cb&&!Ab;this.bLd=!cb&&!gc;this.aLd||this.bLd||(this.JKd=!cb,this.IKd=!Ab,this.HKd=!gc)}b.r(F);C=b(0);var U=b(37),Z=b(675),ca=b(15),ra=b(128);Object(C.a)(da,"RenameDisabledDialogInfo",null,[]);var La=ra.StandardDialog;Em(V,La);V.prototype.X$i=function(){this.B0.aLd?this.LHb(this.Fpa?this.moa?CommonUIStrings.l_RenameFileRenameReadOnlyRecommended:CommonUIStrings.l_RenameFileRenameNotEveryoneSupportsRename:
CommonUIStrings.l_RenameFileRenameDisabledCoauthFull):this.B0.bLd?this.LHb(CommonUIStrings.l_RenameFileRenameDisabledPermissionFull):this.$og();this.Ppa(this.VNd)};V.prototype.LHb=function(cb){Array.add(this.VNd,cb)};V.prototype.$og=function(){var cb=[];this.B0.JKd||Array.add(cb,CommonUIStrings.l_RenameFileRenameDisabledSignIn);this.B0.IKd||Array.add(cb,CommonUIStrings.l_RenameFileRenameDisabledPermission);this.B0.HKd||Array.add(cb,CommonUIStrings.l_RenameFileRenameDisabledCoauth);0<cb.length&&Array.add(this.VNd,
cb)};Object(C.a)(V,"ReactRenameDisabledDialogBase",ra.StandardDialog,[]);Em(Y,V);Y.prototype.AWi=function(){this.Kyb(CommonUIStrings.l_RenameFileRenameDisabledTitle,null,null,null,null,null)};Object(C.a)(Y,"ReactRenameDisabledDialog",V,[]);var na=b(140);Ll.Object.defineProperties(N,{tf:{configurable:!0,enumerable:!0,get:function(){return na.a.$i(N.Jj,CommonUIStrings.l_RenameFileRenameDisabled,CommonUIStrings.l_RenameFileRenameDisabledSignIn,CommonUIStrings.l_RenameFileRenameDisabledPermission,CommonUIStrings.l_RenameFileRenameDisabledCoauth)}}});
N.Jj="<div class='WACDialogRow' id='RenameRow'> <label id='labelDisabledMessage' class='WACDialogLabel' >{0}</label> <div class='WACDialogRow' id='MultipleSuggestionsRow'> <ul id='ulRenameFileDisabled' class='WACDialogUList'> <li id='liRenameFileRenameDisabledSignIn'>{1}</li> <li id='liRenameFileRenameDisabledPermission'>{2}</li> <li id='liRenameFileRenameDisabledCoauth'>{3}</li> </ul> </div> </div>";Object(C.a)(N,"RenameDisabledDialogHtml",null,[]);var ma=na.a;Em(G,ma);G.prototype.x6a=function(){if(this.B0.aLd){var cb=
this.Fpa?this.moa?CommonUIStrings.l_RenameFileRenameReadOnlyRecommended:CommonUIStrings.l_RenameFileRenameNotEveryoneSupportsRename:CommonUIStrings.l_RenameFileRenameDisabledCoauthFull;G.LHb(document.getElementById("ulRenameFileDisabled"),document.getElementById("labelDisabledMessage"),cb)}else this.B0.bLd?G.LHb(document.getElementById("ulRenameFileDisabled"),document.getElementById("labelDisabledMessage"),CommonUIStrings.l_RenameFileRenameDisabledPermissionFull):this.GRh()};G.prototype.GRh=function(){this.B0.JKd&&
(document.getElementById("liRenameFileRenameDisabledSignIn").style.display="none");this.B0.IKd&&(document.getElementById("liRenameFileRenameDisabledPermission").style.display="none");this.B0.HKd&&(document.getElementById("liRenameFileRenameDisabledCoauth").style.display="none")};G.LHb=function(cb,Ab,gc){cb.style.display="none";Ab.innerText=gc};Object(C.a)(G,"RenameDisabledDialog",na.a,[]);var xa=b(5),Pa=b(30),ib=b(108),pb=b(28);W.prototype.initialize=function(cb){if(!this.La||!this.h7)return!1;this.kCa=
cb;this.Lg();return!0};W.prototype.Lg=function(){this.La.Xb(pb.a.uga,ib.a.frame,Object(U.a)(this,this.uga,"commitNewDocumentTitle"))};W.prototype.uga=function(cb,Ab,gc,Lc,Nc){if(1===gc)return this.La.processAction(pb.a.renameFile,1);cb=Pa.a.Bq(this.h7.fn);Nc=(0,Nc.getNewDocumentTitle)();Nc.length>this.kCa&&(Nc=Nc.substr(0,this.kCa));if(32!==this.La.Ge(pb.a.renameFile,2,Nc))return this.mW(cb),8;this.mW(Nc);return 32};W.prototype.mW=function(cb){appChrome.api.dispatch(appChrome.actions.updateDocumentTitle(cb))};
W.f$c=function(){return new W(xa.AFrameworkApplication.Hb,xa.AFrameworkApplication.nl)};Object(C.a)(W,"ReactRenameUIHandler",null,[285]);var xb=b(816),Ya=b(901),ab=b(572),ea=b(13),ta=b(117),Ka=b(167),mb=b(87),Ha=b(48),Ga=b(23),Fa=b(88);fa.prototype.initialize=function(cb,Ab,gc){if(!(this.La&&this.h7&&this.b9d&&this.bSb&&this.yAc&&Ab)||0>=cb)return!1;this._element=Ab;this._element.title=gc;this._element.setAttribute(mb.a.Od,mb.a.Zq);this._element.setAttribute("Unselectable","on");this.kCa=cb;this.tx();
return this._initialized=!0};fa.prototype.tx=function(){this.Gzc&&(this.Gzc.pa(ea.a.blur,this._element,Object(U.a)(this,this.onBlur,"onBlur")),this.Gzc.pa(ea.a.paste,this._element,Object(U.a)(this,this.onPaste,"onPaste")));this.de.pa(ea.a.Qb,this._element,Object(U.a)(this,this.onKeyDown,"onKeyDown"));this.pz.pa(ea.a.pointerDown,this._element,Object(U.a)(this,this.onPointerDown,"onPointerDown"));this.pz.pa(ea.a.Ud,this._element,Object(U.a)(this,this.Ah,"onPointerUp"))};fa.prototype.onBlur=function(){this.isActive&&
!this.pEc&&(this.N1d||this.yAc(this._element),this.Bse(),this.c0c(!1));return this.pEc=!1};fa.prototype.onPaste=function(){ca.ULS.sendTraceTag(4281482,203,15,"Attempting to paste into the document title");return!0};fa.prototype.onKeyDown=function(cb){return this.isActive?this.nvi(cb):this.ovi(cb)};fa.prototype.nvi=function(cb){var Ab=!1;switch(cb.Ea.keyCode){case Sys.UI.Key.enter:this.Bse();this.c0c(this.GTa||this.iFc);Ab=!0;break;case Sys.UI.Key.tab:this.N1d&&this.yAc(this._element);break;case Sys.UI.Key.esc:this.pEd(),
this.c0c(this.GTa||this.iFc),Ab=!0}return Ab};fa.prototype.ovi=function(cb){var Ab=!1;switch(cb.Ea.keyCode){case Sys.UI.Key.enter:case Sys.UI.Key.space:this.B_f(this.iFc),this.isActive&&this.bSb(this._element),Ab=!0}return Ab};fa.prototype.onPointerDown=function(){this.isActive||(this.B_f(!1),this.isActive&&(this._element.focus(),this.bSb(this._element),this.QKc=!0));return!1};fa.prototype.Ah=function(){return this.QKc?(this.bSb(this._element),this.QKc=!1,!0):!1};fa.prototype.T3a=function(){return 32===
this.La.processAction(pb.a.renameFile,1)};fa.prototype.Bse=function(){var cb=Pa.a.Bq(this.h7.fn),Ab=this._element.innerText.trim();Ab.length>this.kCa&&(Ab=Ab.substr(0,this.kCa));Ab!==cb&&""!==Ab?32!==this.La.Ge(pb.a.renameFile,2,Ab)?this.pEd():this.mW(Ab):this.pEd()};fa.prototype.pEd=function(){this.mW(Pa.a.Bq(this.h7.fn))};fa.prototype.mW=function(cb){this._initialized&&(this._element.innerText=cb,this.b9d())};fa.prototype.B_f=function(cb){this.T3a()?this.isActive||(cb&&(this.pEc=!0,this._element.blur()),
this._element.setAttribute("contentEditable","true"),this._element.removeAttribute("Unselectable"),this._element.setAttribute(mb.a.Od,mb.a.uRc),this._element.style.width="auto",Sys.UI.DomElement.addCssClass(this._element,xb.CuiHelper.QBe),this.s7&&this.s7.execute(function(Ab){Ab.zAf(!0)}),cb&&this._element.focus(),ca.ULS.sendTraceTag(9234188,203,50,"Rename document from header.")):this.La.processAction(pb.a.kab,2)};fa.prototype.c0c=function(cb){this._element.removeAttribute("contentEditable");this._element.setAttribute("Unselectable",
"on");this._element.setAttribute(mb.a.Od,mb.a.Zq);Sys.UI.DomElement.removeCssClass(this._element,xb.CuiHelper.QBe);this.s7&&this.s7.execute(function(Ab){Ab.zAf(!1)});cb&&(this._element.blur(),this._element.focus())};fa.wx=function(){Ya.a.wx(xa.AFrameworkApplication.isRtl)};fa.f$c=function(){return new fa(xa.AFrameworkApplication.Hb,ab.a.instance,ta.KeyInputManager.instance,Ka.a.instance,xa.AFrameworkApplication.nl,fa.wx,Ha.a.r3i,Ha.a.BLg,Fa.a.instance.oc("Common.App.Header.HeaderEventSource"),Ga.a.KG,
Ga.a.ah,Ga.a.uf)};Ll.Object.defineProperties(fa.prototype,{isActive:{configurable:!0,enumerable:!0,get:function(){return"true"===this._element.getAttribute("contentEditable")}}});Object(C.a)(fa,"RenameUIHandler",null,[285]);Ll.Object.defineProperties(aa,{instance:{configurable:!0,enumerable:!0,get:function(){return xa.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled?aa.Ma||(aa.Ma=W.f$c()):aa.Ma||(aa.Ma=fa.f$c())}}});aa.Ma=null;Object(C.a)(aa,"RenameUIHandlerFactory",null,[]);var eb=b(93);
Object(C.a)(L,"RenameMruEntryProperties",null,[]);var db=b(519),Na=b(178),kb=b(678),Tb;(function(cb){cb[cb.unknown=-1]="unknown";cb[cb.success=0]="success";cb[cb.renameInvalidFileName=1]="renameInvalidFileName";cb[cb.renameInCoauthNotSupported=2]="renameInCoauthNotSupported";cb[cb.renameNotSupportedInViewMode=3]="renameNotSupportedInViewMode";cb[cb.permissionDenied=4]="permissionDenied";cb[cb.serverCommunicationFailure=5]="serverCommunicationFailure";cb[cb.fileNameTooLong=6]="fileNameTooLong"})(Tb||
(Tb={}));Object(C.b)("CommonOperationResult",Tb);Q.prototype.Lg=function(){xa.AFrameworkApplication.xa&&xa.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled||this.pi.Xb(pb.a.Nub,ib.a.frame,Object(U.a)(this,this.Nub,"initializeRenameUIHandler"));this.pi.Xb(pb.a.kab,ib.a.frame,Object(U.a)(this,this.kab,"showRenameDisabledDialog"));this.pi.Xb(pb.a.renameFile,ib.a.frame,Object(U.a)(this,this.renameFile,"renameFile"));this.pi.Af(pb.a.fileNameUpdate,ib.a.frame,Object(U.a)(this,this.xPi,"refreshFilename"),
64);this.pi.Af(pb.a.Agc,ib.a.frame,Object(U.a)(this,this.Agc,"moveToFolderCompleteByHost"),64);this.pi.Xb(pb.a.VLa,ib.a.frame,Object(U.a)(this,this.VLa,"moveToFolder"));xa.AFrameworkApplication.xa&&(xa.AFrameworkApplication.ha.sa("PostMessageEmbedded")||xa.AFrameworkApplication.ha.sa("IsJsApi"))&&xa.AFrameworkApplication.ha.getBooleanFeatureGate("Microsoft.Office.SharedOnline.MoveRenameProcess",!0)&&xa.AFrameworkApplication.yY().execute(function(cb){cb.En(Na.a.Cgf);cb.xm(Na.a.Cgf,Q.wOi);cb.En(Na.a.H5c);
cb.xm(Na.a.H5c,Q.uOi)})};Q.prototype.T3a=function(){return this.lig.RTe()?8:32};Q.prototype.gAj=function(){return this.Vx?this.Fpa?this.Vx.NAe:this.Vx.yrb:!0};Q.prototype.Nub=function(){return aa.instance.initialize(xa.AFrameworkApplication.b5b,xa.AFrameworkApplication.AZa,xa.AFrameworkApplication.OCd||CommonUIStrings.l_RenameFileTooltip)?32:8};Q.prototype.kab=function(){var cb=this.gAj(),Ab=this.Rlg();ca.ULS.sendTraceTag(4059649,203,50,"ShowRenameDisabledDialog: userIsAnonymous = {0}, userCanRename = {1}, userCanRenameInCurrentSession = {2}, userCanRenameInCoauthSessionsWithRenameCapableUsers = {3}",
this.eCa,Ab,cb,this.Fpa);xa.AFrameworkApplication.xa&&xa.AFrameworkApplication.xa.Xa.qu&&xa.AFrameworkApplication.ha.sa("ReactRenameDisabledDialogIsEnabled")?new Y(this.eCa,!Ab,!cb,this.Fpa,this.moa()):new G(this.eCa,!Ab,!cb,this.Fpa,this.moa());return 32};Q.prototype.renameFile=function(cb,Ab,gc,Lc,Nc){if(1===gc)return this.T3a();if(!xa.AFrameworkApplication.x4b)return 8;if(8===this.T3a())return this.pi.processAction(pb.a.kab,2),8;ca.ULS.sendTraceTag(38114562,203,50,"RenameFileAttempt");xa.AFrameworkApplication.x4b(Nc,
Object(U.a)(this,this.VAb,"onRenameFileSuccess"),Object(U.a)(this,this.$xi,"onRenameFileFailure"));return 32};Q.prototype.VAb=function(cb,Ab){cb?cb.OperationResult?this.CXe(cb.OperationResult):(this.M4i(Ab,cb.NewName),this.Svj(cb,Object(U.a)(xa.AFrameworkApplication.xa.Xa,xa.AFrameworkApplication.xa.Xa.U2f,"updateOpenInClientDocumentUrl")),xa.AFrameworkApplication.ha.sa("DocumentNameInJewelInfoMenuIsEnabled")&&xa.AFrameworkApplication.xa.updateCommandUI(),this.mig.A1f()):this.CXe(5)};Q.prototype.M4i=
function(cb,Ab){var gc={};gc[db.a.jlh]=Ab;cb.Vj(Na.a.H5c,gc)};Q.prototype.Svj=function(cb,Ab){this.cwj(cb);xa.AFrameworkApplication.b2b=cb.DirectInvokeDavUrl;Ab=Ab(cb.EditDocInClientUrl);var gc=new L;gc.Jki=this.Vu.fn;gc.rZg=Ab;gc.Fki=cb.EditDocInClientUrl;this.pi.Ge(pb.a.renameMostRecentlyUsedFileEntry,2,gc)};Q.prototype.CXe=function(cb){switch(cb){case 1:cb=new ra.StandardDialog,cb.hc=0,cb.WV(CommonUIStrings.l_RenameFileInvalidNameTitle,CommonUIStrings.l_RenameFileInvalidName,null),this.IIf()}};
Q.prototype.cwj=function(cb){this.Vu.fn=Q.mxg(this.Vu.fn,cb.NewName);cb.BreadcrumbFolderName&&(this.Vu.breadcrumbFolderName=cb.BreadcrumbFolderName);cb.BreadcrumbFolderUrl&&(this.Vu.breadcrumbFolderUrl=cb.BreadcrumbFolderUrl);this.$ae(cb.NewName)};Q.prototype.$xi=function(cb){var Ab=new ra.StandardDialog;Ab.hc=0;switch(cb){case 1:ca.ULS.sendTraceTag(38114563,203,50,"OnRenameFileFailure: InvalidFileName");Ab.Pya(CommonUIStrings.l_RenameFileInvalidNameTitle,CommonUIStrings.l_RenameFileInvalidName,null);
break;case 6:ca.ULS.sendTraceTag(38114564,203,50,"OnRenameFileFailure: FileNameTooLong");Ab.Pya(CommonUIStrings.l_RenameFileInvalidNameTitle,CommonUIStrings.l_RenameFileNameTooLong,null);break;default:var gc={};ca.ULS.sendTraceTag(38114565,203,15,"OnRenameFileFailure: {0}",(gc.Result=cb,gc));Ab.Pya(CommonUIStrings.l_RenameFileGenericErrorTitle,CommonUIStrings.l_RenameFileGenericError,null)}xa.AFrameworkApplication.yY().execute(function(Lc){var Nc={};Lc.Vj(Na.a.ilh,(Nc.FailureMessage=Tb[cb],Nc))});
this.IIf()};Q.prototype.xPi=function(cb,Ab,gc){if(1===gc)return this.T3a();if(!xa.AFrameworkApplication.hHa)return 8;xa.AFrameworkApplication.hHa(Object(U.a)(this,this.Yic,"onRefreshFilenameSuccess"),Object(U.a)(this,this.Xic,"onRefreshFilenameFailure"),!1);return 32};Q.prototype.VLa=function(cb,Ab,gc,Lc,Nc){if(1===gc)return xa.AFrameworkApplication.ha.getBooleanFeatureGate("Microsoft.Office.SharedOnline.DTTMoveButton",!1)&&xa.AFrameworkApplication.ha.sa("UiHostSupportsMoveToFolder")?32:8;if(2===
gc){var yd={};cb=xa.AFrameworkApplication.pja;Ab=xa.AFrameworkApplication.ha.sa("UiHostSupportsDocRebootFeatures");cb=(!cb||cb&&Ab)&&xa.AFrameworkApplication.ha.getBooleanFeatureGate("Microsoft.Office.SharedOnline.CrossSiteMove",!1);yd[db.a.enj]=cb;Nc&&Nc.MoveButtonClickedTime&&(yd[db.a.gji]=Nc.MoveButtonClickedTime.getTime());xa.AFrameworkApplication.yY().execute(function(Od){Od.Vj(Na.a.VLa,yd)});if(Nc&&Nc.MoveButtonClickedTime){if(cb=this.fs())Nc=(new Date).getTime()-Nc.MoveButtonClickedTime.getTime(),
cb.set("MovePostDuration",Nc.toString());eb.Health.instance.recordKpiUsage("MoveToFolder",0,"smartfio",cb)}return 32}return 8};Q.prototype.Agc=function(cb,Ab,gc,Lc,Nc){if(1===gc)return xa.AFrameworkApplication.ha.sa("UiHostSupportsMoveToFolder")?this.T3a():8;if(2===gc){if(!xa.AFrameworkApplication.fMf)return eb.Health.instance.recordKpiFailure("MoveToFolder","Null SendFileNameAndLocationUpdateNotification",!1,!1,null),8;if(!Nc)return eb.Health.instance.recordKpiFailure("MoveToFolder","Null actiondata",
!1,!1,null),8;if(Nc[db.a.C0h])if(Nc[db.a.O3f])if(cb=Nc[db.a.O3f].toLowerCase(),Ab=xa.AFrameworkApplication.ha.sa("UiHostSupportsDocRebootFeatures"),gc=xa.AFrameworkApplication.ha.getBooleanFeatureGate("Microsoft.Office.SharedOnline.CrossSiteMove",!1),Ab&&xa.AFrameworkApplication.pja&&gc){var yd={};yd[db.a.GNa]="1";yd[db.a.documentUrl]=cb;yd[db.a.reason]=kb.a.saveAs;eb.Health.instance.recordKpiSuccess("MoveToFolder",null);xa.AFrameworkApplication.yY().execute(function(Od){Od.Vj(Na.a.Vra,yd)})}else if(!xa.AFrameworkApplication.pja&&
gc)eb.Health.instance.recordKpiSuccess("MoveToFolder",null),Ha.a.lf(cb,Ha.a.pW(3),void 0,"RenameActor.MoveToFolderCompleteByHost");else return eb.Health.instance.recordKpiFailure("MoveToFolder","CrossSite Unsupported",!1,!1,null),8;else eb.Health.instance.recordKpiFailure("MoveToFolder","Null newDocUrl",!1,!1,null);else xa.AFrameworkApplication.hHa(Object(U.a)(this,this.Yic,"onRefreshFilenameSuccess"),Object(U.a)(this,this.Xic,"onRefreshFilenameFailure"),!1),xa.AFrameworkApplication.fMf(),eb.Health.instance.recordKpiSuccess("MoveToFolder",
null)}return 32};Q.prototype.bfj=function(cb,Ab){return cb&&Ab?cb!==this.Vu.breadcrumbFolderName||Ab!==this.Vu.breadcrumbFolderUrl:!1};Q.prototype.Yic=function(cb,Ab){cb&&(cb.NewName!==Pa.a.Bq(this.Vu.fn)||this.bfj(cb.BreadcrumbFolderName,cb.BreadcrumbFolderUrl))&&this.VAb(cb,Ab)};Q.prototype.Xic=function(){};Q.prototype.IIf=function(){this.$ae(Pa.a.Bq(this.Vu.fn))};Q.prototype.fs=function(){try{return new Map}catch(cb){return null}};Q.zrb=function(){return new Q(xa.AFrameworkApplication.U3a,new Z.a(function(){return xa.AFrameworkApplication.Hb}),
new Z.a(function(){return xa.AFrameworkApplication.Vx}),xa.AFrameworkApplication.nl,xa.AFrameworkApplication.limitedEdit,function(){return xa.AFrameworkApplication.userCanRename},xa.AFrameworkApplication.wnc,Object(U.a)(aa.instance,aa.instance.mW,"updateTitle"),Fa.a.instance.resolve("Common.App.Rename.IRenamedFileChecker"),function(){return xa.AFrameworkApplication.isReadOnlyRecommended},xa.AFrameworkApplication.ha,Fa.a.instance.resolve("Common.IRenameProps"))};Q.mxg=function(cb,Ab){cb=Pa.a.g3(cb);
return Ab+cb};Q.wOi=function(cb){var Ab=cb.Values[db.a.Q3h];ca.ULS.sendTraceTag(560820289,204,50,"Host_MoveToFolder Received IsSuccessful: {0}",Ab);Ab?xa.AFrameworkApplication.Hb.Ge(pb.a.Agc,2,cb.Values):eb.Health.instance.recordKpiFailure("MoveToFolder","MoveToFolder Server Failure",!1,!1,null)};Q.uOi=function(cb){xa.AFrameworkApplication.Hb.Ge(pb.a.renameFile,2,cb.Values.NewName)};Ll.Object.defineProperties(Q.prototype,{pi:{configurable:!0,enumerable:!0,get:function(){return this.La.value}},Vx:{configurable:!0,
enumerable:!0,get:function(){return this.IAc.value}}});Ll.Object.defineProperties(Q,{instance:{configurable:!0,enumerable:!0,get:function(){return Q.Ma||(Q.Ma=Q.zrb())}}});Q.Ma=null;Object(C.a)(Q,"RenameActor",null,[]);b(922);Object(C.a)(function(){},"ActivityEventName",null,[]);S.compatMode="CompatMode";S.noSelection="NoSelection";Object(C.a)(S,"ActivityEventReason",null,[]);var ha=b(677);H.prototype.Lg=function(){this.La.Xb(pb.a.OTf,ib.a.frame,Object(U.a)(this,this.Qhj,"showRenameDialogAction"))};
H.prototype.Qhj=function(cb,Ab,gc){cb=32;if(1===gc)return ha.SessionStatusManager.instance.utb||xa.AFrameworkApplication.nU?8:32;2===gc&&(32!==this.La.processAction(pb.a.renameFile,1)?(this.La.processAction(pb.a.kab,2),cb=8):32===this.La.processAction(pb.a.VKd,1)?this.La.processAction(pb.a.VKd,2):this.OSa.value.create().asc());return cb};Object(C.a)(H,"RenameDialogActor",null,[296]);A.prototype.DGh=function(){var cb={},Ab={};cb.nameInputProps=(Ab.type="AppInputProps",Ab.id=A.zZa,Ab.label=CommonUIStrings.l_RenameDialogLabel,
Ab.value=Pa.a.Bq(this.Vu.fn),Ab.maxLength=this.boa,Ab);return cb};A.prototype.asc=function(){var cb=this.DGh(),Ab={};cb=(Ab.id="RenameDialog",Ab.bodyControls=cb,Ab);this.dialog=new na.a(!1,!1,!0);this.dialog.hc=1;this.dialog.Ie="RenameDialog";this.dialog.initializeAndShow(CommonUIStrings.l_RenameDialogTitle,Object(U.a)(this,this.MCd,"renameDialogHandler"),cb)};A.prototype.MCd=function(cb,Ab){Ab&&1===cb&&Ab[A.zZa]&&(cb=Pa.a.Bq(this.Vu.fn),Ab=(Ab[A.zZa]||"").trim(),Ab!==cb&&""!==Ab&&this.La.Ge(pb.a.renameFile,
2,Ab))};A.zZa="txtDocumentName";Object(C.a)(A,"ReactRenameDialog",null,[325]);Ll.Object.defineProperties(E,{tf:{configurable:!0,enumerable:!0,get:function(){return na.a.$i(E.Jj,CommonUIStrings.l_RenameDialogLabel)}}});E.Jj="<div class='WACDialogRow' id='DocumentNameBlock'> <label id='lblDocumentName' class='WACDialogLabel' for='txtDocumentName' >{0}</label> <input type='text' id='txtDocumentName' class='WACDialogInput' autocomplete=\"off\"/> </div>";Object(C.a)(E,"RenameDialogHtml",null,[]);var lb=
na.a;Em(J,lb);J.prototype.asc=function(){var cb={};cb=(cb.txtDocumentName=Pa.a.Bq(this.Vu.fn),cb);this.initializeAndShow(CommonUIStrings.l_RenameDialogTitle,Object(U.a)(this,this.MCd,"renameDialogHandler"),cb);cb=document.getElementById(J.zZa);0<this.boa&&(cb.maxLength=this.boa);cb.focus()};J.prototype.MCd=function(cb,Ab){1===cb&&(cb=Pa.a.Bq(this.Vu.fn),Ab=(Ab[J.zZa]||"").trim(),Ab!==cb&&""!==Ab&&this.La.Ge(pb.a.renameFile,2,Ab))};J.zZa="txtDocumentName";Object(C.a)(J,"RenameDialog",na.a,[325]);y.prototype.initialize=
function(cb,Ab){this.h7=cb;this.boa=Ab;this._initialized=!0};y.prototype.create=function(){return this._initialized?xa.AFrameworkApplication.xa&&xa.AFrameworkApplication.xa.Xa.qu&&xa.AFrameworkApplication.ha.sa("ReactRenameDialogIsEnabled")?new A(this.La,this.h7,this.boa):new J(this.La,this.h7,this.boa):null};Object(C.a)(y,"RenameDialogFactory",null,[297]);var Wa=b(213);x.prototype.Lg=function(){this.La.Xb(pb.a.VKd,ib.a.frame,Object(U.a)(this,this.Rhj,"showRenameFlyoutAction"))};x.prototype.HHg=function(){return Wa.appChromeContainsAction("setDocumentTitleFlyoutOpened")&&
xa.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled};x.prototype.Rhj=function(cb,Ab,gc){if(1===gc)return this.HHg()?32:8;appChrome.api.dispatch(appChrome.actions.setDocumentTitleFlyoutOpened(!0));return 32};Object(C.a)(x,"RenameFlyoutActor",null,[293]);z.prototype.RTe=function(){if(!this.Y1d())return 5;if(this.moa())return 1;if(this.Vx){if(this.Z1d&&!this.Vx.NAe)return 3;if(!this.Z1d&&!this.Vx.yrb)return 4}return this.Vlg()?0:2};Ll.Object.defineProperties(z.prototype,{Vx:{configurable:!0,
enumerable:!0,get:function(){return this.IAc.value}}});Object(C.a)(z,"RenameProps",null,[275]);b(211);var Ra=b(106);B.prototype.enable=function(){this.gl||(this.A1f(),this.rMd(),this.gl=!0)};B.prototype.generateKey=function(cb,Ab,gc){return String.format("{0}/{1}/{2}",gc,cb,Ab)};B.prototype.$Bh=function(){var cb=Pa.a.Bq(this.USa().fn);return this.generateKey(this.USa().breadcrumbFolderName,this.USa().breadcrumbFolderUrl,cb)};B.prototype.aCh=function(cb,Ab,gc){return cb&&Ab?this.generateKey(cb,Ab,
gc):gc};B.prototype.K2g=function(cb,Ab,gc){return cb&&cb!==this.USa().breadcrumbFolderName||Ab&&Ab!==this.USa().breadcrumbFolderUrl?!0:gc!==Pa.a.Bq(this.USa().fn)};B.prototype.A1f=function(){var cb=this.$Bh();this.HGc.ia(cb,new Date)};B.prototype.swd=function(cb){this.Mdj(cb)&&this.hce(cb)};B.prototype.Mdj=function(cb){var Ab=this.dag();return Ab?this.I$d&&this.I$d.Rvb||!Ab.O4e||!xa.AFrameworkApplication.hHa?(this.eWf(cb),this.gl=!1):!0:!1};B.prototype.Vsf=function(cb,Ab,gc,Lc){var Nc=this.K2g(cb,
Ab,gc);cb=this.aCh(cb,Ab,gc);Ab=this.HGc.zc(cb).returnValue;Nc&&!Ab&&(this.DXe(Lc),ca.ULS.sendTraceTag(591734297,203,50,"{0} forced FileNameUpdate",this.Ind));Nc||this.HGc.ia(cb,this.EK())};Object(C.a)(B,"ARenamedFileChecker",null,[248]);Em(t,B);t.prototype.rMd=function(){this.V7d.MPc(Object(U.a)(this,this.jYe,"handleSettingsRefresh"))};t.prototype.jYe=function(cb,Ab){Ab&&Ab.ezb&&Ab.Fni&&(Ab.c4a("BreadcrumbDocName")||Ab.c4a("BreadcrumbFolderName")||Ab.c4a("BreadcrumbFolderUrl")||Ab.c4a("DirectInvokeDAVUrl")||
Ab.c4a("EditDocInClientUrl"))&&(ca.ULS.sendTraceTag(591229211,203,50,"{0}: Possible rename detected.",this.Ind),this.swd(Ab))};t.prototype.eWf=function(){this.V7d.dVi(Object(U.a)(this,this.jYe,"handleSettingsRefresh"))};t.prototype.hce=function(cb){if(cb&&cb.ezb){var Ab=cb.ezb;this.Vsf(Ab.Ta("BreadcrumbFolderName"),Ab.Ta("BreadcrumbFolderUrl"),Ab.Ta("BreadcrumbDocName"),cb)}};t.prototype.DXe=function(cb){var Ab=this,gc={OperationResult:0,classId:1};cb=cb.ezb;gc.BreadcrumbFolderName=cb.Ta("BreadcrumbFolderName");
gc.BreadcrumbFolderUrl=cb.Ta("BreadcrumbFolderUrl");gc.DirectInvokeDavUrl=cb.Ta("DirectInvokeDAVUrl");gc.EditDocInClientUrl=cb.Ta("EditDocInClientUrl");cb=cb.Ta("BreadcrumbDocName");gc.NewName=xa.AFrameworkApplication.AGa?cb:Pa.a.Bq(cb);this.Ldg.execute(function(Lc){Ab.qZh(gc,Lc)})};t.prototype.qZh=function(cb,Ab){this.kig().VAb(cb,Ab)};Ll.Object.defineProperties(t.prototype,{Ind:{configurable:!0,enumerable:!0,get:function(){return"RenamedFileCheckerUsingSettingsRefresh"}}});Object(C.a)(t,"RenamedFileCheckerUsingSettingsRefresh",
B,[]);var Yb=b(109);Em(w,B);w.prototype.xRi=function(cb){this.FTb=cb;this.FTb.Otg(Object(U.a)(this,this.zcd,"handleVisibilityChange"))};w.prototype.zcd=function(cb,Ab){!this.gl||Ab.newState&&1!==Ab.newState||this.dib||(this.rMd(),this.swd(this.dib))};w.prototype.rMd=function(){this.dib=new Yb.a(3,2,this.thg(),Object(U.a)(this,this.swd,"performRenameFileCheckTick"),89);this.fe.kh(this.dib)};w.prototype.eWf=function(cb){this.fe.cp(cb)};w.prototype.hce=function(cb){this.FTb&&2===this.FTb.WEj?this.uSi(cb):
xa.AFrameworkApplication.hHa(Object(U.a)(this,this.Yic,"onRefreshFilenameSuccess"),Object(U.a)(this,this.Xic,"onRefreshFilenameFailure"),!0)};w.prototype.uSi=function(cb){this.fe.cp(cb);this.dib=null};w.prototype.Yic=function(cb){cb&&this.Vsf(cb.BreadcrumbFolderName,cb.BreadcrumbFolderUrl,cb.NewName,null)};w.prototype.DXe=function(){this.La.processAction(pb.a.fileNameUpdate,2)};w.prototype.Xic=function(){};Ll.Object.defineProperties(w.prototype,{Ind:{configurable:!0,enumerable:!0,get:function(){return"RenamedFileCheckerUsingTask"}}});
Object(C.a)(w,"RenamedFileCheckerUsingTask",B,[]);v.prototype.Qh=function(cb){var Ab=this;this.Za=cb;this.vb=xa.AFrameworkApplication.ha;this.Za.register(H,"Common.App.Rename.RenameDialogActor").as("Common.App.Rename.IRenameDialogActor").Fc(function(){return new H(xa.AFrameworkApplication.Hb,Ab.Za.jEd("Common.App.Rename.IRenameDialogFactory"))}).wc();this.Za.register(y,"Common.App.Rename.RenameDialogFactory").as("Common.App.Rename.IRenameDialogFactory").Fc(function(){return new y(xa.AFrameworkApplication.Hb)}).wc();
this.Za.register(248,"Common.App.Rename.IRenamedFileChecker").Fc(function(){return Ab.bXg()}).wc();this.Za.register(x,"Common.App.Rename.RenameFlyoutActor").as("Common.App.Rename.IRenameFlyoutActor").Fc(function(){return new x(xa.AFrameworkApplication.Hb)}).wc()};v.prototype.bXg=function(){var cb=this;if(this.vb.sa("RenamedFileCheckerWithSettingsRefreshIsEnabled")){var Ab=this.Za.Mh("Common.IRefreshableAppSettings");if(Ab&&Ab.o5h)return new t(function(){return Ab.xd("RenamedFileCheckerMaxCachedAgeInMs",
48E4)},function(){return xa.AFrameworkApplication.nl},function(){return new Date},function(){return xa.AFrameworkApplication.Vx},Ab,this.Za.Mh("Common.ISessionStatus"),function(){return Q.instance},this.Za.oc("Postmessage.IHostPostmessenger"))}return new w(function(){return cb.vb.xd("RenamedFileCheckerMaxCachedAgeInMs",48E4)},function(){return cb.vb.xd("RenamedFileCheckerPingIntervalInMs",12E4)},function(){return xa.AFrameworkApplication.nl},function(){return new Date},function(){return xa.AFrameworkApplication.Vx},
xa.AFrameworkApplication.ha,xa.AFrameworkApplication.Hb,xa.AFrameworkApplication.sj,this.Za.Mh("Common.ISessionStatus"),this.Za.oc("Common.App.VisibilityManagement.IVisibilityManager"))};v.prototype.init=function(){this.vb.Dv(Object(U.a)(this,this.mA,"onFullAppSettingsReady"))};v.prototype.mA=function(){var cb=xa.AFrameworkApplication.xa.Xa.isReactSharedHeaderUxEnabled;xa.AFrameworkApplication.U3a()&&aa.instance.initialize(xa.AFrameworkApplication.b5b,cb?null:xa.AFrameworkApplication.AZa,cb?null:
xa.AFrameworkApplication.OCd||CommonUIStrings.l_RenameFileTooltip)&&(this.Za.register(z,"Common.App.Rename.RenameProps").as("Common.IRenameProps").Fc(function(){return new z(function(){return xa.AFrameworkApplication.userCanRename},function(){return xa.AFrameworkApplication.isReadOnlyRecommended},xa.AFrameworkApplication.wnc,xa.AFrameworkApplication.U3a,new Z.a(function(){return xa.AFrameworkApplication.Vx}))}).wc(),Q.instance.Lg(),this.vb.sa("RenameDialogIsEnabled")&&(this.Za.resolve("Common.App.Rename.RenameDialogFactory").initialize(xa.AFrameworkApplication.nl,
xa.AFrameworkApplication.b5b),this.Za.resolve("Common.App.Rename.IRenameDialogActor").Lg()),this.Za.resolve("Common.App.Rename.IRenameFlyoutActor").Lg(),xa.AFrameworkApplication.wnc&&this.Za.resolve("Common.App.Rename.IRenamedFileChecker").enable())};v.prototype.dispose=function(){};Ll.Object.defineProperties(v.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.RenameFile"}}});Object(C.a)(v,"PackageManager",null,[8,9]);F=b(276);var oc=b(12),zb=b(800),uc=b(58),P=b(35),
lc=b(57),Ec=b(173),tc=b(51);h.prototype.executeCommand=function(cb,Ab,gc){switch(Ab.command){case pb.a.uga:return lc.a.Df.isReactSharedHeaderUxEnabled?2!==xa.AFrameworkApplication.Hb.Ge(pb.a.uga,2,gc)?tc.Task.Ra(!0):Ec.a(Ab.command):Ec.a(Ab.command);case 1897077126:return this.renameFileManager.renameFile(gc,Ab),tc.Task.Ra(!0);default:return Ec.a(Ab.command)}};h.prototype.Ec=function(cb,Ab,gc,Lc){switch(Ab.command){case pb.a.uga:return lc.a.Df.isReactSharedHeaderUxEnabled;case 1897077126:return!!Lc&&
2===Lc.Ez}return!1};h.prototype.Yc=function(){return!1};h.prototype.Wc=function(){return!1};h.prototype.dispose=function(){this.renameFileManager=null};Object(C.a)(h,"RenameFileCommandHandler",null,[160,6]);var cc=zb.a;Em(r,cc);r.prototype.Gd=function(){var cb=this,Ab=uc.GetServiceTaskFactory.create(this.$.ea,119,this.la,this.rb,"Microsoft.Office.Excel.WebUI.Client.RenameFile.IRenameFileManager");P.TaskExtensions.Aa(Ab,function(){cb.Ad([new h(Ab.result)])},this.la,3)};r.ja=function(cb){zb.a.Yd(118,
new r(cb))};Object(C.a)(r,"RenameFileCommandHandlerFactory",zb.a,[]);var Zb=b(86),Aa=b(212),Ia=b(220),qb=b(74),wb=b(373),ic=b(79),Jb=b(364),Ua=b(161),$a=b(92),ua=b(303),Ca=b(1),Sa=b(7),Qb=b(275);Ll.Object.defineProperties(n.prototype,{O4e:{configurable:!0,enumerable:!0,get:function(){return this.$.workbookContext.FileCoauthorable}},Rvb:{configurable:!0,enumerable:!0,get:function(){return!1}},yrb:{configurable:!0,enumerable:!0,get:function(){return this.$.fa.amIAlone}},NAe:{configurable:!0,enumerable:!0,
get:function(){if(this.yrb)return!0;for(var cb=Ol(this.$.fa.tm),Ab=cb.next();!Ab.done;Ab=cb.next())if(!Ab.value.SupportsRename)return!1;return!0}}});Object(C.a)(n,"EwaCoauthManager",null,[276]);var Hb=b(81),Db=b(64),jc=qb.a;Em(l,jc);l.prototype.initialize=function(){xa.AFrameworkApplication.x4b=Object(U.a)(this,this.Iri,"onExecuteRenameFile");xa.AFrameworkApplication.hHa=Object(U.a)(this,this.Hri,"onExecuteRefreshFilename");this.k0c=xa.AFrameworkApplication.Vx;xa.AFrameworkApplication.Vx=new n(this.$)};
l.prototype.dispose=function(){xa.AFrameworkApplication.x4b=null;xa.AFrameworkApplication.hHa=null;this.$.fa.Qv(Object(U.a)(this,this.uia,"handleWorkbookMetadataChanged"));xa.AFrameworkApplication.Vx=this.k0c;this.$=this.k0c=null;jc.prototype.dispose.call(this)};l.prototype.uia=function(){var cb=this.$.fa.qn;if(cb&&!Sa.a.ma(cb.WorkbookFileName)){var Ab=Pa.a.Bq(cb.WorkbookFileName),gc=!!Sa.a.compare(this.$.workbookContext.WorkbookFileName,cb.WorkbookFileName,!1),Lc=Ca.EwaSettings.ka(572)&&!Sa.a.ma(cb.BreadcrumbFolderUrl)&&
!!Sa.a.compare(this.$.workbookContext.FullDocumentInfo.BreadcrumbFolderUrl,cb.BreadcrumbFolderUrl,!1);if(gc||Lc)this.Bba={},this.Bba.NewFileName=Ab,this.Bba.EditDocInClientUrl=cb.EditDocInClientUrl,this.Bba.DirectInvokeDAVUrl=cb.DirectInvokeDAVUrl,this.Bba.DownloadACopyUrl=cb.DownloadACopyUrl,Ca.EwaSettings.ka(572)&&!Sa.a.ma(cb.BreadcrumbFolderUrl)&&(this.Bba.BreadcrumbFolderName=cb.BreadcrumbFolderName,this.Bba.BreadcrumbFolderUrl=cb.BreadcrumbFolderUrl),cb=xa.AFrameworkApplication.Hb.Ge(pb.a.fileNameUpdate,
2,Ab),this.Bba=null,ca.ULS.shipAssertTag(537154064,0,32===cb,"RenameFileManager.HandleWorkbookMetadataChanged - Workbook Name Update Failed")}};l.prototype.renameFile=function(cb,Ab){var gc=this,Lc=cb.newFileName;if(!Sa.a.ma(Lc)){var Nc=this.$.ra.ua.Wb();Jb.a(this.$.userOperationManager,function(yd,Od,sa){var vb=gc.$.ra.ua;yd=Qb.b(yd,Object(U.a)(gc,gc.VAb,"onRenameFileSuccess"));Od=Qb.a(Od,Object(U.a)(gc,gc.Zxi,"onRenameFileFail"));var Lb=vb.Na(9,Nc);Lb.newFileName=Lc;return Hb.i(vb,"RenameFile",
Lb,yd,Od,sa,null,0)},function(yd){return new Ua.a(134,0,yd)},Ab)}};l.prototype.n0h=function(){return 32===xa.AFrameworkApplication.Hb.processAction(pb.a.uga,1)};l.prototype.Iri=function(cb,Ab,gc){this.cGf=Ab;this.NCd=gc;Ab={};this.$.Ka.Ub(new $a.a(1897077126,ic.a.Tb,2,3,null),(Ab.newFileName=cb,Ab))};l.prototype.Hri=function(cb){this.Bba&&cb(this.STe(this.Bba),this.rr)};l.prototype.VAb=function(cb){ua.a(cb)||!cb.Result?(cb=l.jsh(cb),Db.a(this.$).fd.Rjb([-414480287,650565124,-782844485,1223808266,
-62451516,1636785843]),this.NCd(cb)):this.cGf(this.STe(cb.Result),this.rr)};l.prototype.STe=function(cb){var Ab=this.$.workbookContext;xa.AFrameworkApplication.A2=cb.DownloadACopyUrl;var gc=Ca.EwaSettings.ka(572)&&!Sa.a.ma(cb.BreadcrumbFolderUrl);gc&&(xa.AFrameworkApplication.nl.breadcrumbFolderName=cb.BreadcrumbFolderName,xa.AFrameworkApplication.nl.breadcrumbFolderUrl=cb.BreadcrumbFolderUrl,Ab.FullDocumentInfo.BreadcrumbFolderUrl=cb.BreadcrumbFolderUrl,Ab.FullDocumentInfo.BreadcrumbFolderName=cb.BreadcrumbFolderName);
Ab.FullDocumentInfo.BreadcrumbDocName=cb.NewFileName;wb.d(Ab,cb.NewFileName);Ab={};Ab.NewName=cb.NewFileName;Ab.DirectInvokeDavUrl=cb.DirectInvokeDAVUrl;Ab.EditDocInClientUrl=cb.EditDocInClientUrl;gc&&(Ab.BreadcrumbFolderName=cb.BreadcrumbFolderName,Ab.BreadcrumbFolderUrl=cb.BreadcrumbFolderUrl);Ab.OperationResult=0;return Ab};l.prototype.Zxi=function(){this.NCd(5)};l.jsh=function(cb){switch(cb.Errors[0].MessageId){case -414480287:cb=2;break;case 650565124:cb=1;break;case 1636785843:cb=6;break;case -782844485:cb=
4;break;default:cb=5}return cb};Object(C.a)(l,"RenameFileManager",qb.a,[255,6]);var sb=b(49),fb=Aa.a;Em(d,fb);d.prototype.create=function(){var cb=this;if(!this.PX){var Ab=Ia.a.OYa(sb.b(),this.la,"Task","IRenameFileManager");this.PX=Ab.task;var gc=uc.GetServiceTaskFactory.create(this.$.ea,137,this.la,this.rb,"Postmessage.IHostPostmessenger"),Lc=uc.GetServiceTaskFactory.create(this.$.ea,155,this.la,this.rb,"System.Dictionary");P.TaskExtensions.Aa(P.TaskExtensions.xe([Lc,gc],this.la),function(){var Nc=
new l(cb.$,gc.result);cb.$.ea.Ia(120,Nc);Ab.setResult(Nc)},this.la,3)}this.PX.continueWith(function(Nc){cb.Eb(Nc.result)})};d.prototype.dispose=function(){Zb.a.Fa(this.renameFileManager);this.$=this.renameFileManager=null;fb.prototype.dispose.call(this)};d.ja=function(cb){cb.ea.Ia(119,new d(cb))};Object(C.a)(d,"RenameFileManagerServiceFactory",Aa.a,[]);e.prototype.Wc=function(){return!1};e.prototype.executeCommand=function(cb,Ab,gc){return 2!==this.pi.Ge(pb.a.OTf,2,gc)?tc.Task.Ra(!0):Ec.a(Ab.command)};
e.prototype.Ec=function(cb,Ab){return 1204860550===Ab.command};e.prototype.Yc=function(){return!1};Object(C.a)(e,"RenameFileDialogCommandHandler",null,[160]);var Qa=zb.a;Em(a,Qa);a.prototype.Gd=function(){var cb=this;P.TaskExtensions.Aa(uc.GetServiceTaskFactory.create(this.$.ea,155,this.la,this.rb,"System.Dictionary"),function(){cb.Ad([new e(xa.AFrameworkApplication.Hb)])},this.la,3)};a.ja=function(cb){zb.a.Yd(131,new a(cb))};Object(C.a)(a,"RenameFileDialogCommandHandlerFactory",zb.a,[]);Type.registerNamespace("_Ewa");
Type.registerNamespace("Common.App.Rename");F.a.instance.ej(new v,7);(function(){oc.a.Ga(function(cb){d.ja(cb);r.ja(cb)})})();oc.a.Ga(a.ja)}}]);

//# sourceMappingURL=EwaDS.rn.js.map