(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[27],{1229:function(C,F,b){function a(h,v,w){this.DMc=0;this.XPb=null;this.gcb=this.tTb=this.Beb=0;this.BLc=h;this.aUa=v;this.b8=w;this.BLc=262144>h?h:262144;this.Yfg=this.BLc-4*(this.aUa+25);this.reset()}function e(h,v,w,t,B,z,x,y,J){y=void 0===y?null:y;J=void 0===J?null:J;this.T=this.G=0;this.C=this.M=null;this.D=0;this.G=z;this.T=t;this.M=h;this.C=v;this.D=1E3*B+w;if(void 0===x?0:x)this.O=1;y&&(this.A=y);J&&(this.E=J)}function d(h,
v,w,t,B){this.T=h;this.L=v;this.S=w;this.I=t;this.V=B}function l(h,v,w,t,B,z){h&&(this.N=h);v&&(this.S=v);w&&(this.M=w);t&&(this.F=t);null!=B&&(this.L=B);null!=z&&(this.C=z)}b.r(F);C=b(0);var n=b(15);Object(C.a)(l,"SerializableExceptionEntry",null,[]);Object(C.a)(d,"SerializableLogCache",null,[]);e.prototype.uJg=function(){if(!this.E)return 0;var h=7,v=0;this.E.N&&(h+=6+e.T8(this.E.N),v++);this.E.S&&(h+=6+e.T8(this.E.S),v++);this.E.M&&(h+=6+e.T8(this.E.M),v++);this.E.F&&(h+=6+e.T8(this.E.F),v++);
this.E.L&&(h+=6+e.T8(this.E.L),v++);this.E.C&&(h+=6+e.T8(this.E.C),v++);1<v&&(h+=v-1);return h};e.prototype.IOg=function(){var h=b(1229).LogCache.xci+e.T8(this.G)+e.T8(this.T)+this.M.length+e.T8(this.C)+e.T8(this.D)+this.uJg();1===this.O&&(h+=6);if(this.A){h+=7;for(var v=0,w=this.A.length;v<w;++v)h+=this.A[v].length+3}return h};e.T8=function(h){return(""+h).length};Object(C.a)(e,"SerializableLogEntry",null,[]);var r=b(580);b.d(F,"LogCache",function(){return a});a.prototype.reset=function(){this.XPb=
[];this.Beb=25;this.DMc=(new Date).getTime()};a.prototype.cpg=function(h){if(h){h.message=this.EJb(h.message,"message",h.tag);var v=h.D4c;v&&(v.name=this.EJb(v.name,"Exception.Name",h.tag),v.stack=this.EJb(v.stack,"Exception.Stack",h.tag),v.message=this.EJb(v.message,"Exception.Message",h.tag),v.file=this.EJb(v.file,"Exception.File",h.tag));if(h.Jg)for(var w=0;w<h.Jg.length;w++)h.Jg[w].length>this.aUa&&(h.Jg[w]=h.Jg[w].substr(0,this.aUa-13)+"... [trimmed]",n.ULS.sendTraceTag(3465240,100,50,"Trimmed arg {0} for log {1}",
w,r.a(h.tag)));v=v?new l(v.name,v.stack,v.message,v.file,v.line,v.column):null;h=new e(h.message,h.category,h.level,h.timestamp-this.DMc,h.hfc,h.tag,h.G3h,h.Jg,v);v=h.IOg();0<this.tTb&&v+this.Beb>this.tTb&&(w=this.count,this.reset(),n.ULS.sendTraceTag(0,100,15,"The log size is too large to be accepted by the server, throwing away {0} logs.",w));Array.add(this.XPb,h);this.Beb+=v}};a.prototype.EJb=function(h,v,w){var t=h;h&&h.length>this.aUa&&(t=h.substr(0,this.aUa-13)+"... [trimmed]",n.ULS.sendTraceTag(3465240,
100,50,"Trimmed {0} for log {1}",v,r.a(w)));return t};a.prototype.serialize=function(){return n.ULS.Hc(new d(this.DMc,this.XPb,this.b8,this.gcb,1))};Ll.Object.defineProperties(a.prototype,{count:{configurable:!0,enumerable:!0,get:function(){return this.XPb.length}},ywc:{configurable:!0,enumerable:!0,get:function(){return this.tTb},set:function(h){this.tTb=h}},J0h:{configurable:!0,enumerable:!0,get:function(){return this.Beb>this.Yfg}},rLd:{configurable:!0,enumerable:!0,get:function(){return this.BLc}},
Bnd:{configurable:!0,enumerable:!0,get:function(){return this.aUa}}});a.xci=31;Object(C.a)(a,"LogCache",null,[64,65])},1379:function(C,F,b){function a(Fa){this.f5d=null;this.D8h=Fa}function e(Fa){var eb=ta.call(this)||this;eb.gca=Fa;eb.Yb();return eb}function d(Fa){var eb=ea.call(this)||this;eb.VZb=Fa;Sys.Application.registerDisposableObject(eb);return eb}function l(){}function n(Fa){Fa=r.call(this,Fa,!1,aa.AFrameworkApplication.Cd,xa.a.instance.Mh("Common.IRefreshableAppSettings")||aa.AFrameworkApplication.ha,
xa.a.instance.Mh("Common.IRefreshableAppSettings"))||this;Fa.cuj="usu";Fa.$tj="ufu";Fa.ub=null;Fa.Oa=new xb.a;return Fa}function r(Fa,eb,db,Na,kb){Fa=w.call(this,aa.AFrameworkApplication.userSessionId,r.Sqh(Fa,eb,db),new t(void 0,aa.AFrameworkApplication.yLh(),Na.xd("BulsUploadFrequencyInMs",6E4),void 0,void 0,void 0,void 0,aa.AFrameworkApplication.PXb))||this;Fa.pF=null;Fa.Wib=null;Fa.eKc=null;Fa.Ng=db;Fa.BAa=Na;Fa.Tib=Fa.BAa.Ta("RemoteUlsETag");Fa.Tib&&r.ezf(Fa.BAa.Ta("RemoteUlsSuppressions"));
kb&&kb.MPc(Object(H.a)(Fa,Fa.qzi,"onSettingsRefreshed"));return Fa}function h(Fa){var eb=ib.call(this)||this;eb.Jg=Fa;return eb}function v(Fa,eb,db,Na){this.gcb=Fa;this.Hke=eb;this.sessionId=db;this.version=Na}function w(Fa,eb,db){db=void 0===db?null:db;this.hjb=this.jzb=this.lOb=0;this.Ig=null;this.kId=this._disposing=!1;this.YA=this.AMc=this.MMb=this.FNb=0;this.Dpc=!1;this.lSa=0;db||(db=new t);this.XKc=Fa;this.D6=eb;this.D6.toLowerCase().startsWith("http:")&&document.URL.toLowerCase().startsWith("https:")&&
A.ULS.disable();this.Llg=db.P3f;this.llg=db.MYf;this.pbg=db.Jye;this.Mlg=db.pke;this.X9f=db.mke;this.Coa=new na.LogCache(db.rLd,db.Bnd,Fa);this.Coa.ywc=db.ywc;this.KDd();this.ENb=[];this.WHf()}function t(Fa,eb,db,Na,kb,Tb,ha,lb){Fa=void 0===Fa?null:Fa;eb=void 0===eb?null:eb;db=void 0===db?null:db;Na=void 0===Na?null:Na;kb=void 0===kb?null:kb;Tb=void 0===Tb?null:Tb;ha=void 0===ha?null:ha;lb=void 0===lb?null:lb;this.Bnd=3072;this.rLd=65536;this.P3f=6E4;this.MYf=2E3;this.Jye=1E4;this.pke=5E3;this.mke=
!1;this.ywc=0;null!=Fa&&(this.Bnd=Fa);null!=eb&&(this.rLd=eb);null!=db&&(this.P3f=db);null!=Na&&(this.MYf=Na);null!=kb&&(this.Jye=kb);null!=Tb&&(this.pke=Tb);null!=ha&&(this.mke=ha);null!=lb&&0<lb&&(this.ywc=lb)}function B(){}function z(){}function x(Fa,eb,db,Na,kb){this.rDa=Fa;this.iSa=eb;this.h0=db;this.lzc=Na;this.Eeg=kb}function y(){this.File=this.Message=null;this.Column=this.Line=0;this.ClientAppVersion=this.Stack=null;this.AppMode=this.AppType=0;this.DeobfuscateWithSourceMaps=!1;this.DataPlumber=
this.SessionStartInfoJson=null;this.IsShuttingDown=!1;this.ErrorName=this.Flight=null}function J(){this.Za=null}function E(){$addHandler(document,"securitypolicyviolation",Object(H.a)(this,this.$rf,"onSecurityPolicyViolationEventHandler"))}b.r(F);C=b(662);F=b(0);var A=b(15),H=b(37),S=b(78);E.prototype.$rf=function(Fa){Fa=Fa.rawEvent;var eb=Fa.blockedURI;eb=S.a.Lxa(eb);var db={};db.effectiveDirective=Fa.effectiveDirective;db.violatedDirective=Fa.violatedDirective;db.originalPolicy=Fa.originalPolicy;
db.blockedURI=eb;db.disposition=Fa.disposition;A.ULS.sendTraceTag(588084128,306,15,"{0}",db)};E.prototype.dispose=function(){$removeHandler(document,"securitypolicyviolation",Object(H.a)(this,this.$rf,"onSecurityPolicyViolationEventHandler"))};Object(F.a)(E,"ContentSecurityPolicyListener",null,[6]);var Q=b(276);J.prototype.init=function(){this.Za.resolve("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener")};J.prototype.dispose=function(){var Fa=this.Za.Mh("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener");
Fa&&Fa.dispose()};J.prototype.Qh=function(Fa){this.Za=Fa;this.Za.register(E,"Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener").wc().Fc(function(){return new E})};J.main=function(){Q.a.instance.ej(new J)};Ll.Object.defineProperties(J.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.ContentSecurityPolicy"}}});Object(F.a)(J,"ContentSecurityPolicyPackage",null,[8,9]);var L=b(41);y.prototype.IGd=function(){return L.c(this)};Object(F.a)(y,"DiagnosticsRequest",
null,[]);var aa=b(5),fa=b(476),W=b(411),G=b(30);x.prototype.vMf=function(Fa,eb){try{this.JUg().send(this.ksh(Fa,eb))}catch(db){A.ULS.sendTraceTag(6161306,201,10,"Could not send error report [{0}]",db.toString())}};x.prototype.JUg=function(){var Fa=new XMLHttpRequest;Fa.open("POST",this.rDa,!0);Fa.setRequestHeader("Content-Type","text/json; charset=utf-8");aa.AFrameworkApplication.userSessionId&&Fa.setRequestHeader(W.a.Kwc,G.a.Cia(aa.AFrameworkApplication.userSessionId));this.iSa&&Fa.setRequestHeader(W.a.c6a,
this.iSa);if(aa.AFrameworkApplication.Cd){var eb=aa.AFrameworkApplication.Cd.fR;eb&&Fa.setRequestHeader(W.a.hxc,eb)}return Fa};x.prototype.ksh=function(Fa,eb){if(!Fa)return null;eb=eb?"<stack>"+eb+"</stack>":"";var db=new y;db.Message=Fa.message;db.File=Fa.source;db.Line=Fa.line;db.Column=Fa.column;db.Stack=eb;db.ClientAppVersion=this.iSa;db.AppType=this.h0;db.AppMode=this.lzc;db.DeobfuscateWithSourceMaps=this.Eeg;aa.AFrameworkApplication.ha.sa("JavaScriptCrashJsonTagEnabled")&&(db.SessionStartInfoJson=
aa.AFrameworkApplication.ha.appSettings.SessionStartInfoJson||"",aa.AFrameworkApplication.Sf&&(db.DataPlumber=L.c(aa.AFrameworkApplication.Sf)),db.IsShuttingDown=aa.AFrameworkApplication.Fg,db.Flight=aa.AFrameworkApplication.ZI,db.ErrorName=fa.a.vPe(Fa));return db.IGd()};Object(F.a)(x,"JavascriptErrorReporter",null,[398]);z.prototype.build=function(Fa,eb,db,Na,kb){return new x(Fa,eb,db,Na,kb)};Object(F.a)(z,"JavascriptErrorReporterFactory",null,[368]);B.prototype.Qh=function(Fa){Fa.register(z,"Common.App.Diagnostics.JavascriptErrorReporterFactory").as("Common.IJavascriptErrorReporterFactory").wc().Fc(function(){return new z})};
B.prototype.init=function(){};B.prototype.dispose=function(){};B.main=function(){Q.a.instance.ej(new B)};Ll.Object.defineProperties(B.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.Diagnostics"}}});Object(F.a)(B,"DiagnosticsPackage",null,[8,9]);var N=b(52),Y=b(101),V=b(212),da=b(35),U=b(139),Z=b(403),ca=b(36),ra=b(57),La=b(38),na=b(1229);Object(F.a)(t,"UlsUploadConfiguration",null,[]);var ma=b(580);w.prototype.aU=function(Fa){1<this.Kbb?Array.add(this.ENb,Fa):(this.Coa.cpg(Fa),
this.Xci(Fa)&&!this.Qze()?(this.HLe("LogIndicatesError in HandleTrace"),A.ULS.sendTraceTag(3731793,100,200,"Flushing error-level log (tag {0}) synchronously",ma.a(Fa.tag))):this.Coa.J0h&&(this.Rqb(!1,!0),A.ULS.sendTraceTag(3731794,100,200,"Flushing asynchronously due to cache size")))};w.prototype.Xci=function(Fa){return!!Fa&&(1===Fa.hfc||10===Fa.level)};w.prototype.Qze=function(){return!1};w.prototype.dispose=function(){this._disposing||(this._disposing=!0,this.hoh(),A.ULS.nId(null),window.clearTimeout(this.lSa),
window.clearTimeout(this.FNb),window.clearTimeout(this.MMb),this.MMb=this.FNb=this.lSa=0)};w.prototype.hoh=function(){this.mode=2;this.qXe();this.Dpc=!1;this.cDe();this.HLe("FlushForAppClose")};w.prototype.tKb=function(Fa,eb){Fa.gcb=this.jzb;return this.Q3f(Fa.serialize(),eb)?(this.jzb++,!0):!1};w.prototype.Q3f=function(Fa,eb){eb=this.X9f||!eb;this.Ig&&eb||(this.Ig=new XMLHttpRequest);if(!this.Ig.readyState||4===this.Ig.readyState)return this.Ig.open("POST",this.D6,eb),this.Ig.setRequestHeader("Content-Type",
"application/json"),this.Ig.setRequestHeader(w.UGd,this.XKc),eb&&(this.Ig.timeout=this.Mlg),this.Ig.send(Fa),!0;Fa={};A.ULS.sendTraceTag(3731796,100,50,"Could not initiate upload {0}",(Fa.UploadId=this.jzb,Fa.XhrReadyState=this.Ig.readyState,Fa));return!1};w.prototype.mBi=function(){this.Ig&&this.Ig.abort()};w.prototype.Vqc=function(Fa,eb,db){try{return window.setTimeout(function(){A.ULS.sendTraceTag(3731797,100,200,"Timeout ({0} ms) set by {1} is now firing.",eb,db);Fa()},eb)}catch(Na){A.ULS.sendTraceTag(0,
100,15,"SetTimeoutToLogOriginAndExecute: Calling Window.SetTimeout() failed with exception: {0}",Na.toString());if(!this.kId){this.kId=!0;try{Fa()}finally{this.kId=!1}}return 0}};w.prototype.WHf=function(){try{window.clearTimeout(this.FNb)}catch(Fa){A.ULS.sendTraceTag(0,100,15,"ResetDelayedLoggingTimer: Calling Window.ClearTimeout() failed with exception: {0}",Fa.toString())}this.FNb=this.Vqc(Object(H.a)(this,this.qXe,"handleDelayedLogs"),this.pbg,"ResetDelayedLoggingTimer")};w.prototype.qXe=function(){var Fa=
this.ENb.length;if(Fa){var eb=[];Array.addRange(eb,this.ENb);this.ENb=[];var db={};A.ULS.sendTraceTag(3731798,100,50,"HandleDelayedLogs {0}",(db.Count=Fa,db));this.hjb++;for(db=0;db<Fa;db++)this.aU(eb[db]);this.hjb--}this.WHf()};w.prototype.KDd=function(){try{window.clearTimeout(this.MMb)}catch(Fa){A.ULS.sendTraceTag(0,100,15,"ResetCadenceTimer: Calling Window.ClearTimeout() failed with exception: {0}",Fa.toString())}this.MMb=this.Vqc(Object(H.a)(this,this.Rqb,"flushImpl"),this.Llg,"ResetCadenceTimer")};
w.prototype.cDe=function(){this.mode=0;this.Dpc&&(this.Dpc=!1,this.Rqb())};w.prototype.IPa=function(Fa){return 2===this.mode||1===this.mode&&!Fa};w.prototype.HLe=function(Fa){A.ULS.sendTraceTag(3731800,100,200,"Flushing Synchronous due to {0}",Fa);this.Rqb(!0)};w.prototype.Pqb=function(){this.FLe(0)};w.prototype.FLe=function(Fa){this.lSa||(this.lSa=this.Vqc(Object(H.a)(this,this.Rqb,"flushImpl"),Fa,"FlushAsynchronous"))};w.prototype.Rqb=function(Fa,eb){this.hjb++;try{window.clearTimeout(this.lSa)}catch(Na){A.ULS.sendTraceTag(0,
100,15,"FlushImpl: Calling Window.ClearTimeout() failed with exception: {0}",Na.toString())}this.lSa=0;if(this.Coa.count)if(!eb&&this.IPa(Fa))A.ULS.sendTraceTag(3731801,100,200,"Not flushing ({0}) due to throttling",Fa?"sync":"async"),this.Dpc=!0;else{this.mode=Fa?2:1;this.KDd();A.ULS.sendTraceTag(3731803,100,200,"Flushing ({0}) cached bULS logs ({1} logs)",Fa?"sync":"async",this.Coa.count);try{var db=this.tKb(this.Coa,Fa)}catch(Na){this.mBi(),db=!1}db?(this.Coa.reset(),this.lOb=0):(this.lOb++,this.lOb<
w.tff?this.FLe(w.AEd):(this.Coa.reset(),this.jzb++,this.lOb=0))}else this.KDd();this.hjb--};w.prototype.ntb=function(){};w.prototype.zkb=function(){};Ll.Object.defineProperties(w.prototype,{Kbb:{configurable:!0,enumerable:!0,get:function(){return A.ULS.Kbb+this.hjb}},mode:{configurable:!0,enumerable:!0,get:function(){return this.YA},set:function(Fa){var eb=this.YA;this.YA=Fa;if(!this.YA&&eb)try{var db=this.AMc;this.AMc=0;window.clearTimeout(db)}catch(Na){A.ULS.sendTraceTag(0,100,15,"set_Mode: Calling Window.ClearTimeout() failed with exception: {0}",
Na.toString())}else this.YA&&!eb&&(this.AMc=this.Vqc(Object(H.a)(this,this.cDe,"endThrottling"),this.llg,"ThrottlingMode Setter"))}}});w.tff=3;w.AEd=15E3;w.UGd="X-UserSessionId";Object(F.a)(w,"UploadingUlsHost",null,[34,6]);Object(F.a)(v,"UploadState",null,[]);var xa=b(88),Pa=b(553),ib=Sys.EventArgs;Em(h,ib);Object(F.a)(h,"UlsLoggingEventArgs",Sys.EventArgs,[]);var pb=b(122);Em(r,w);r.prototype.zkb=function(Fa){this.events.addHandler(r.A0f,Fa)};r.prototype.qzi=function(Fa,eb){eb.c4a(r.yNd)&&(this.Wib=
this.jVe())};r.prototype.qvh=function(){return Error().stack};r.prototype.jVe=function(){var Fa=null;if(this.BAa.Yx(r.yNd)){Fa=new pb.a;for(var eb=this.BAa.Uw(r.yNd),db=0;db<eb.length;db++)Fa.ia(eb[db],!0)}return Fa};r.prototype.aU=function(Fa){this.Wib||(this.Wib=this.jVe());if(this.Wib&&this.Wib.qb(Fa.tag))try{!Fa.D4c&&this.eSc?Fa.D4c=new Pa.a(Error()):Fa.message+=". JsCallStack: "+this.qvh()}catch(db){Fa.message+=" [Failed to add callstack for this tag. BUlsExceptionLoggingIsEnabled="+this.eSc+
" ("+db.message+")]"}w.prototype.aU.call(this,Fa);var eb=this.events.getHandler(r.A0f);Fa=new h(Fa);eb&&eb(null,Fa)};r.prototype.tKb=function(Fa,eb){if(this.Ng){if(!this.$ej)return!1;var db=Fa.serialize();if(0<aa.AFrameworkApplication.PXb&&db.length>aa.AFrameworkApplication.PXb)return!1;Fa.gcb=this.jzb++;if(this.iej())return this.Ipc(this.D6,db),!0;this.Ree(this.D6,db,eb&&!this.KBb?0:3,1,eb&&aa.AFrameworkApplication.Fg,Fa.gcb,this.KBb,this.Xuf);return!0}return w.prototype.tKb.call(this,Fa,eb)};r.prototype.Sud=
function(Fa){try{if(Fa&&Fa.data&&Fa.data.responseHeaders&&r.V9b in Fa.data.responseHeaders){var eb=Fa.data.responseHeaders[r.V9b];eb!==this.Tib&&(this.Tib=eb,r.ezf(Fa.data.responseHeaders[r.JZe]))}}catch(db){A.ULS.sendTraceTag(593847297,100,50,"Failed to process tag suppressions. [Message: {0}] [Stack: {1}]",db.message,db.stack)}};r.prototype.otd=function(Fa){var eb=this,db=Fa.data;if(!db)A.ULS.sendTraceTag(5002497,100,15,"Request Item is null! RequestFailedEventArgs = {0}",Fa);else if(13===db.status)A.ULS.sendTraceTag(6399108,
100,50,"Request timed out in the ClientRequestManager queue. Falling back to default XHR."),this.Q3f(db.request.get_body(),!1);else if(!db.responseHeaders)A.ULS.sendTraceTag(5002498,100,15,"Item.ResponseHeader is null! RequestItem id = {0}, responseXml = {1}, data = {2}, HttpStatusCode = {3}",db.id,db.jOa,db.ae,db.httpStatus);else if(!(r.TYh in db.responseHeaders||(Fa=db.httpStatus,400<=Fa&&499>=Fa))){var Na=db.state;Na.Hke>=w.tff||window.setTimeout(function(){eb.Ree(db.request.get_url(),db.request.get_body(),
3,Na.Hke+1,!1,Na.gcb,Na.sessionId,Na.version)},w.AEd)}};r.prototype.Ree=function(Fa,eb,db,Na,kb,Tb,ha,lb){this.Ng.Jl(Fa,2,eb,this.zUg(),!1,db,Object(H.a)(this,this.Sud,"onSuccessfulUpload"),Object(H.a)(this,this.otd,"onFailedUpload"),new v(Tb,Na,ha,lb),null,kb,this.BAa.xd("BulsClientRequestManagerQueueTimeInMS",3E4),void 0,"19",ha,void 0,lb,void 0,[r.V9b,r.JZe])};r.prototype.zUg=function(){var Fa=null;this.Tib&&(Fa={},Fa[r.V9b]=this.Tib);if(this.eSc){var eb=aa.AFrameworkApplication.xa,db=null;eb&&
(db=eb.Xa);db&&(Fa||(Fa={}),Fa[r.QQh]=db.dMa,Fa[r.RQh]=db.Tk,Fa[r.WQh]=aa.AFrameworkApplication.c0h?"1":"0")}return Fa};r.prototype.Ipc=function(Fa,eb){this.Ng.Ipc(Fa,eb)};r.prototype.iej=function(){return aa.AFrameworkApplication.Fg||aa.AFrameworkApplication.bkd};r.Sqh=function(Fa,eb,db){Fa=r.Ung(Fa,eb);return Fa=r.Tqg(Fa,db)};r.Tqg=function(Fa,eb){if(!eb)return Fa;eb=eb.fR;return eb?Fa=S.a.$k(Fa,W.a.ixc,eb):Fa};r.Ung=function(Fa,eb){return eb?S.a.$k(Fa,"build",aa.AFrameworkApplication.buildVersion):
Fa};r.ezf=function(Fa){A.ULS.pZb();if(Fa){Fa=Fa.split(",");Fa=Ol(Fa);for(var eb=Fa.next();!eb.done;eb=Fa.next())eb=parseInt(eb.value),!isNaN(eb)&&isFinite(eb)&&A.ULS.WUb(eb)}};Ll.Object.defineProperties(r.prototype,{events:{configurable:!0,enumerable:!0,get:function(){return this.pF||(this.pF=new Sys.EventHandlerList)}},KBb:{configurable:!0,enumerable:!0,get:function(){return null}},Xuf:{configurable:!0,enumerable:!0,get:function(){return null}},eSc:{configurable:!0,enumerable:!0,get:function(){return this.BAa.sa("BUlsExceptionLoggingIsEnabled")}},
v_i:{configurable:!0,enumerable:!0,get:function(){this.eKc||(this.eKc=this.BAa.xd("bULSUploadRetryDelayWhenDisconnectedInMilliseconds",6E4));return this.eKc}},$ej:{configurable:!0,enumerable:!0,get:function(){var Fa=this.Ng.G3a;return Fa&&(new Date).getTime()-this.Ng.U9h.getTime()>=this.v_i?!0:!Fa}}});r.V9b="X-bULS-SuppressionETag";r.JZe="X-bULS-SuppressedTags";r.QQh="X-bULS-OfficeAppMode";r.RQh="X-bULS-OfficeAppType";r.WQh="X-bULS-UseSourceMaps";r.A0f="CommonUlsTraceEventKey";r.yNd="TagCallStackInclusionList";
r.TYh="X-InvalidUlsJson";Object(F.a)(r,"CommonUlsHost",w,[]);var xb=b(94),Ya=b(1);Em(n,r);n.prototype.aU=function(Fa){1===Fa.hfc&&Ya.EwaSettings.isChangeGateEnabled("OfficeVSO:5335621_IdentifyClientAsserts")&&(Fa.message="Assert: "+Fa.message);r.prototype.aU.call(this,Fa)};n.prototype.Qze=function(){return!0};n.prototype.tKb=function(Fa,eb){if(aa.AFrameworkApplication.Fg&&aa.AFrameworkApplication.s9a)return!1;var db=null;this.$&&(db=this.$.Vb.Dc("UserAction","CommonUlsHostOverrides:UploadLogs"));
eb=!aa.AFrameworkApplication.s9a&&eb;Fa=r.prototype.tKb.call(this,Fa,eb);db&&db.stop();return Fa};n.prototype.Sud=function(Fa){r.prototype.Sud.call(this,Fa);this.Oa.raiseEvent(this.cuj,Fa)};n.prototype.otd=function(Fa){r.prototype.otd.call(this,Fa);this.Oa.raiseEvent(this.$tj,Fa)};Ll.Object.defineProperties(n.prototype,{$:{configurable:!0,enumerable:!0,get:function(){this.ub||(this.ub=0<ra.a.getRegisteredEwaInstances().length?ra.a.pr(document.body):null);return this.ub}}});Object(F.a)(n,"CommonUlsHostOverrides",
r,[365,34,6]);l.prototype.VSg=function(Fa){return new n(Fa)};Object(F.a)(l,"CommonHostFactory",null,[396]);var ab=b(53),ea=ca.a;Em(d,ea);d.prototype.zkb=function(Fa){this.VZb.zkb(Fa)};d.prototype.aU=function(Fa){this.VZb.aU(Fa)};d.prototype.ntb=function(Fa){this.VZb.ntb(Fa)};d.prototype.Pqb=function(){this.VZb.Pqb()};d.ja=function(Fa,eb){eb=void 0===eb?null:eb;var db=new U.a;Object(Z.a)(d,aa.AFrameworkApplication.CQa)||(eb=eb||new l,La.a.cWh(function(){if(aa.AFrameworkApplication.browserUlsIsEnabled){var Na=
Fa+"/RemoteUls.ashx";d.$&&(Na=d.fqg(Na));Na=eb.VSg(Na);aa.AFrameworkApplication.CQa=Na;A.ULS.oPa(50);A.ULS.nId(Na);db.setResult(new d(Na))}else A.ULS.disable()},!aa.AFrameworkApplication.edj()));return db.task};d.fqg=function(Fa){var eb=d.$&&ab.d(d.$)?d.$.workbookContext.BuildVersion:d.$.ya.BuildVersion;return S.a.$k(Fa,"officeserverversion",eb)};Ll.Object.defineProperties(d,{$:{configurable:!0,enumerable:!0,get:function(){d.ub||(d.ub=0<ra.a.getRegisteredEwaInstances().length?ra.a.pr(document.body):
null);return d.ub}}});d.ub=null;Object(F.a)(d,"EwaUlsHost",ca.a,[365,34,6]);var ta=V.a;Em(e,ta);e.prototype.create=function(){var Fa=this;da.TaskExtensions.Aa(d.ja(this.gca),function(eb){eb=eb.result;Y.a.Ji.Ia(135,eb);Fa.Eb(eb)},this.la)};Object(F.a)(e,"EwaUlsHostFactory",V.a,[]);var Ka=b(149),mb=b(32),Ha=b(7);a.prototype.AJi=function(Fa,eb,db){Fa||Ha.a.ma(eb.source)||(Fa=mb.a.yn(this.qrd,eb.source)+1,this.qrd[eb.source]=Fa,Fa-1&Fa||A.ULS.sendTraceTag(537155536,0,15,"{0} errors seen for location={1}",
Fa,eb.source));if(Ha.a.ma(eb.source)||1===mb.a.yn(this.qrd,eb.source,1))A.ULS.sendTraceTag(537155535,0,50,"JavaSctipCrashProcessor.ProcessJavascriptError: Sending request to log JavaScript crash in the server"),this.D8h.vMf(eb,db)};Ll.Object.defineProperties(a.prototype,{qrd:{configurable:!0,enumerable:!0,get:function(){return this.f5d||(this.f5d={})}}});Object(F.a)(a,"JavaScriptCrashProcessor",null,[218]);var Ga=b(61);Type.registerNamespace("_Ewa");Object(C.a)();Type.registerNamespace("Common.App.ContentSecurityPolicy");
J.main();Type.registerNamespace("Common.App.Diagnostics");B.main();Type.registerNamespace("DiagUse");Y.a.Ji.Ia(43,new e(N.a.current.lH.ServerUriBase));(function(){try{Ka.a.pWe().CWCT(function(Fa){try{if(Y.a.Ji.Ba(42))A.ULS.sendTraceTag(537155532,0,50,"JavaScriptCrashProcessorBootstrapper: already initialized");else{var eb=Fa.result,db=xa.a.instance.resolve("Common.IJavascriptErrorReporterFactory").build(N.a.current.lH.ServerUriBase+eb.LayoutsRelativeUri+"/diagnostics.ashx",eb.BuildVersion,1,0,!0);
Y.a.Ji.Ia(42,new a(db));A.ULS.sendTraceTag(537155533,0,50,"JavaScriptCrashProcessorBootstrapper: initialized and ready to be used")}}catch(Na){A.ULS.sendTraceTag(537155531,0,15,"JavaScriptCrashProcessorBootstrapper: An exception occured while initializing JavascriptErrorProcessor, Message: {0}, Callstack: {1}",Na.message,Na.stack)}},null,3,Ga.a.current)}catch(Fa){A.ULS.sendTraceTag(537155530,0,15,"JavaScriptCrashProcessorBootstrapper: an exception occured, Message: {0}, Callstack: {1}",Fa.message,
Fa.stack)}})()}}]);

//# sourceMappingURL=EwaDS.tmcore.js.map